name: Testsuite Preview

on:
  pull_request:

permissions:
  pull_requests: write

jobs:
  ts_preview:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
      RUSTDOCFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          submodules: true

      - name: Generate old report
        run: |
          TESTSUITE_SAVE=1 cargo test -- spec_tests --show-output
          cp testsuite_report.json old.json
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Generate new report
        run: |
         TESTSUITE_SAVE=1 cargo test -- spec_tests --show-output
         cp testsuite_report.json new.json
      - name: Compare reports
        run: python3 ./ci_tools/compare_reports.py old.json new.json > testsuite_report.md

      - name: Sticky Pull Request Comment
        uses: marocchino/sticky-pull-request-comment@v2.9.1
        with:
          header: testsuite
          path: testsuite_report.md
